//! Generated wrappers (ADR 0007, question 2).
//!
//! A wrapper is generated from `exec` plus `env`, never versioned. The generated header
//! is load-bearing, not decoration: it is what proves a wrapper on disk is ours, which
//! lets `plan` report `drifted` rather than `conflict` when its content has changed.

use crate::manifest::Wrapper;

pub const HEADER: &str = "# generated by dotflies — do not edit; change the manifest instead";

/// The exact bytes dotflies would write for this wrapper on this platform.
/// `None` when the wrapper declares nothing for it.
pub fn render(w: &Wrapper, platform: &str) -> Option<String> {
    let exec = w.exec.get(platform)?;

    let mut out = String::from("#!/bin/sh\n");
    out.push_str(HEADER);
    out.push('\n');

    if let Some(note) = &w.note {
        for line in note.lines() {
            out.push_str("# ");
            out.push_str(line);
            out.push('\n');
        }
    }

    if !w.env.is_empty() {
        out.push('\n');
        // BTreeMap: sorted, so the output is stable and diffs stay readable.
        for (key, value) in &w.env {
            out.push_str(&format!("export {key}={}\n", shell_quote(value)));
        }
    }

    out.push_str(&format!("\nexec {} \"$@\"\n", shell_quote(exec)));
    Some(out)
}

/// Single-quote for /bin/sh, escaping embedded quotes the POSIX way. Values come from a
/// manifest, so they are trusted — but a path with a space must still survive.
fn shell_quote(value: &str) -> String {
    if !value.is_empty()
        && value
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || "._-/=:".contains(c))
    {
        return value.to_string();
    }
    format!("'{}'", value.replace('\'', r"'\''"))
}

pub fn is_ours(content: &str) -> bool {
    content.contains(HEADER)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::ByPlatform;
    use std::collections::BTreeMap;

    fn meld() -> Wrapper {
        let mut env = BTreeMap::new();
        env.insert("GSETTINGS_BACKEND".into(), "keyfile".into());
        Wrapper {
            target: ByPlatform {
                darwin: Some("~/.local/bin/meld".into()),
                linux: None,
            },
            exec: ByPlatform {
                darwin: Some("/Applications/Meld.app/Contents/MacOS/Meld".into()),
                linux: None,
            },
            env,
            note: None,
        }
    }

    #[test]
    fn renders_env_then_exec() {
        let out = render(&meld(), "darwin").unwrap();
        assert!(out.starts_with("#!/bin/sh\n"));
        assert!(out.contains("export GSETTINGS_BACKEND=keyfile"));
        assert!(out.contains("exec /Applications/Meld.app/Contents/MacOS/Meld \"$@\""));
        let env_at = out.find("export GSETTINGS_BACKEND").unwrap();
        let exec_at = out.find("exec /Applications").unwrap();
        assert!(env_at < exec_at, "the variable must be set before exec");
    }

    #[test]
    fn a_platform_it_declares_nothing_for_renders_nothing() {
        assert!(render(&meld(), "linux").is_none());
    }

    #[test]
    fn generated_wrappers_identify_themselves() {
        assert!(is_ours(&render(&meld(), "darwin").unwrap()));
        assert!(!is_ours("#!/bin/sh\nexec /usr/bin/meld\n"));
    }

    #[test]
    fn paths_with_spaces_survive_quoting() {
        let mut w = meld();
        w.exec.darwin = Some("/Applications/My App.app/Contents/MacOS/X".into());
        let out = render(&w, "darwin").unwrap();
        assert!(out.contains("exec '/Applications/My App.app/Contents/MacOS/X' \"$@\""));
    }

    #[test]
    fn rendering_is_deterministic() {
        assert_eq!(render(&meld(), "darwin"), render(&meld(), "darwin"));
    }
}
